my_unique_ids = [3494533, 4667808, 4801358, 7792607, 6910589, ]

num_votes = 1
force_it_votes = 14

post_url = "http://www.couponsock.com/submit_vote"
get_url = 'http://www.couponsock.com/store-coupons/wagwalking.com'
write_file = 'wagcodes.html'

upvote_comments = [
        'Worked for me',
        'worked for me',
        'Got my free walk, good experience!',
        'Lockbox is cool, excited for my dog\'s first walk',
        'used this today, credit for a 30 minute walk is in my account',
        'Worked as described',
        'worked as described',
        'Great deal',
        'great deal',
        'this was a good way to try wag for free',
        '+1',
        'Used this to set up a walk for the weekend. Seamless process',
        'love it!',
        'Worked',
        'works',
        'still works',
        'code still active',
        'This worked great for me',
        'Just redeemed this, worked for me',
        '👍',
        'Just used this, I see the credit in my account. Excited to use!',
        'No problems',
        'Works as described',
        'Got to try Wag for freee with this. Worked perfectly.',
        'Works!',
        'Got my free walk',
        'Pup had a great walk that I didn\'t have to pay for! Great deal.',
        'Cute lockbox, free walk. +1',
        '🐺',
        '🐩',
        '🐕',
        'Good deal',
        'Got my free walk, thanks!',
        'Saved me $$ when I needed a last-minute walk, thanks.',
        'worked.',
        'worked',
        'Worked',
        'Worked!',
        'Thanks!',
        'worked as described, free walk + lockbox',
        'Worked for me, got a free walk & lockbox',
        'Worked! Got credit for a free walk (or other service, looks like) and a lockbox.',
        '💯',
        '🐶 loved it!',
        'just redeemed, worked fine',
        'Works as expected',
        'No problems!',
        'no problems',
        'Great way to check out wag - had a good first walk and the lockbox is a nice touch',
        'Awesome',
        'Good code',
        'Valid',
        'valid',
        'Worked in NYC',
        'Worked for me in the Bay Area!',
        'Worked for me in San Francisco!',
        'Worked for me in Berkeley!',
        'Worked for me in Oakland!',
        'Worked for me in Silicon Valley!',
        'Worked for me in Southern California!',
        'Worked for me in Los Angeles!',
        'Worked for me in Beverly Hills!',
        'Worked for me in Burbank!',
        'Worked for me in Glendale!',
        'Worked for me in Santa Monica!',
        'Worked for me in West Hollywood!',
        'Worked for me in Orange County!',
        'Worked for me in San Diego!',
        'Worked for me in New York City!',
        'Worked for me in Manhattan!',
        'Worked for me in Brooklyn!',
        'Worked for me in Queens!',
        'Worked for me in Staten Island!',
        'Worked for me in Austin!',
        'Worked for me in Chicago!',
        'Worked for me in Seattle!',
        'worked for me in the Bay Area',
        'worked for me in San Francisco',
        'worked for me in Berkeley',
        'worked for me in Oakland',
        'worked for me in Silicon Valley',
        'worked for me in Southern California',
        'worked for me in Los Angeles',
        'worked for me in Beverly Hills',
        'worked for me in Burbank',
        'worked for me in Glendale',
        'worked for me in Santa Monica',
        'worked for me in West Hollywood',
        'worked for me in Orange County',
        'worked for me in San Diego',
        'worked for me in New York City',
        'worked for me in Manhattan',
        'worked for me in Brooklyn',
        'worked for me in Queens',
        'worked for me in Staten Island',
        'worked for me in Austin',
        'worked for me in Chicago',
        'worked for me in Seattle',
        'used today, still works! (Bay Area) ',
        'used today, still works! (San Francisco) ',
        'used today, still works! (Berkeley) ',
        'used today, still works! (Oakland) ',
        'used today, still works! (Silicon Valley) ',
        'used today, still works! (Southern California) ',
        'used today, still works! (Los Angeles) ',
        'used today, still works! (Beverly Hills) ',
        'used today, still works! (Burbank) ',
        'used today, still works! (Glendale) ',
        'used today, still works! (Santa Monica) ',
        'used today, still works! (West Hollywood) ',
        'used today, still works! (Orange County) ',
        'used today, still works! (San Diego) ',
        'used today, still works! (New York City) ',
        'used today, still works! (Manhattan) ',
        'used today, still works! (Brooklyn) ',
        'used today, still works! (Queens) ',
        'used today, still works! (Staten Island) ',
        'used today, still works! (Austin) ',
        'used today, still works! (Chicago) ',
        'used today, still works! (Seattle) ',
        'I live in the Bay Area and this worked great for me today',
        'I live in San Francisco and this worked great for me today',
        'I live in Berkeley and this worked great for me today',
        'I live in Oakland and this worked great for me today',
        'I live in Silicon Valley and this worked great for me today',
        'I live in Southern California and this worked great for me today',
        'I live in Los Angeles and this worked great for me today',
        'I live in Beverly Hills and this worked great for me today',
        'I live in Burbank and this worked great for me today',
        'I live in Glendale and this worked great for me today',
        'I live in Santa Monica and this worked great for me today',
        'I live in West Hollywood and this worked great for me today',
        'I live in Orange County and this worked great for me today',
        'I live in San Diego and this worked great for me today',
        'I live in New York City and this worked great for me today',
        'I live in Manhattan and this worked great for me today',
        'I live in Brooklyn and this worked great for me today',
        'I live in Queens and this worked great for me today',
        'I live in Staten Island and this worked great for me today',
        'I live in Austin and this worked great for me today',
        'I live in Chicago and this worked great for me today',
        'I live in Seattle and this worked great for me today',
        'I live in the Bay Area and this worked for me',
        'I live in San Francisco and this worked for me',
        'I live in Berkeley and this worked for me',
        'I live in Oakland and this worked for me',
        'I live in Silicon Valley and this worked for me',
        'I live in Southern California and this worked for me',
        'I live in Los Angeles and this worked for me',
        'I live in Beverly Hills and this worked for me',
        'I live in Burbank and this worked for me',
        'I live in Glendale and this worked for me',
        'I live in Santa Monica and this worked for me',
        'I live in West Hollywood and this worked for me',
        'I live in Orange County and this worked for me',
        'I live in San Diego and this worked for me',
        'I live in New York City and this worked for me',
        'I live in Manhattan and this worked for me',
        'I live in Brooklyn and this worked for me',
        'I live in Queens and this worked for me',
        'I live in Staten Island and this worked for me',
        'I live in Austin and this worked for me',
        'I live in Chicago and this worked for me',
        'I live in Seattle and this worked for me',
        'Just enter in payment section (will still need cc info for tips & future use). Worked great.',
    ]

downvote_comments = [
        '.',
        ','
        '-.-',
        'Didn\'t work for me',
        'Didn\'t work for me.',
        'Didn\'t work for me',
        'didn\'t work for me',
        'didn\'t work for me',
        'Coudn\'t use in my city',
        'Coudn\'t use in my city.',
        'did not work where i live :(',
        'bummer, no wag for me',
        'Not where I live',
        'not in my town',
        'Not in my city',
        'not for me',
        'only for first time clients?!?',
        'Only for new users :(',
        'nope',
        'Nope',
        'negative',
        'Negative',
        'Bummer',
        'Couldn\'t get this to work',
        'n/a',
        '-',
        ':(',
        'no luck',
        'No luck',
        'N/A for me',
    ]